blank_issues_enabled: false
contact_links:
  - name: Feature Requests & Questions
    url: https://github.com/tannerlinsley/react-table/discussions
    about: Please ask and answer questions here.
  - name: Community Chat
    url: https://discord.gg/2K7RXHm
    about: A dedicated discord server hosted by Tanner Linsley
